version: '3'
services:
  
  bitcoind:
    container_name: bitcoind
    image: "destrys/bitcoind"
    ports:
      - 18443:18443             # Regtest RPC
      - 18332:18332             # Testnet RPC
      - 18333:18333             # Testnet Bitcoin network
    volumes:
      - ./.bitcoin:/home/bitcoin/.bitcoin

